// packages/svelte/src/lib/components/progress/progress-label.svelte
<script module lang="ts">
  import type { HTMLProps, PolymorphicProps, RefAttribute } from '$lib/types'

  export interface ProgressLabelBaseProps extends PolymorphicProps<'span'>, RefAttribute {}
  export interface ProgressLabelProps extends HTMLProps<'span'>, ProgressLabelBaseProps {}
</script>

<script lang="ts">
  import { mergeProps } from '@zag-js/svelte'
  import { Ark } from '../factory'
  import { useProgressContext } from './use-progress-context'

  let { ref = $bindable(null), ...props }: ProgressLabelProps = $props()
  const progress = useProgressContext()
  const mergedProps = $derived(mergeProps(progress().getLabelProps(), props))
</script>

<Ark as="span" bind:ref {...mergedProps} />

// packages/react/src/components/progress/progress-label.tsx
import { mergeProps } from '@zag-js/react'
import { forwardRef } from 'react'
import { type HTMLProps, type PolymorphicProps, ark } from '../factory'
import { useProgressContext } from './use-progress-context'

export interface ProgressLabelBaseProps extends PolymorphicProps {}
export interface ProgressLabelProps extends HTMLProps<'span'>, ProgressLabelBaseProps {}

export const ProgressLabel = forwardRef<HTMLSpanElement, ProgressLabelProps>((props, ref) => {
  const progress = useProgressContext()
  const mergedProps = mergeProps(progress.getLabelProps(), props)

  return <ark.span {...mergedProps} ref={ref} />
})

ProgressLabel.displayName = 'ProgressLabel'
