// packages/vue/src/components/format/format-time.vue
<script lang="ts">
import type { FormatTimeOptions } from '@zag-js/i18n-utils'

export interface FormatTimeProps extends FormatTimeOptions {
  /**
   * The time to format
   */
  value: string | Date
}
</script>

<script setup lang="ts">
import { formatTime } from '@zag-js/i18n-utils'
import { computed } from 'vue'
import { DEFAULT_LOCALE, useLocaleContext } from '../../providers'

const props = defineProps<FormatTimeProps>()
const locale = useLocaleContext(DEFAULT_LOCALE)
const text = computed(() => {
  const { value, ...intlProps } = props
  return formatTime(value, locale.value.locale, intlProps)
})
</script>

<template>
  {{ text }}
</template>

// packages/react/src/components/format/format-time.tsx
import { formatTime, type FormatTimeOptions } from '@zag-js/i18n-utils'
import { useMemo } from 'react'
import { useLocaleContext } from '../../providers/locale'

export interface FormatTimeProps extends FormatTimeOptions {
  /**
   * The time to format
   */
  value: string | Date
}

export const FormatTime = (props: FormatTimeProps) => {
  const { locale } = useLocaleContext()
  const text = useMemo(() => {
    const { value, ...intlOptions } = props
    return formatTime(value, locale, intlOptions)
  }, [props, locale])
  return <>{text}</>
}

FormatTime.displayName = 'FormatTime'
