// packages/vue/src/components/format/examples/time-with-am-pm-labels.vue
<script setup lang="ts">
import { Format } from '@ark-ui/vue/format'
import styles from 'styles/format.module.css'
</script>

<template>
  <div :class="styles.Inline">
    <span :class="styles.InlineLabel">Support window</span>
    <span :class="styles.InlineValue">
      <Format.Time value="17:15:00" :format="'12h'" :am-pm-labels="{ am: 'morning', pm: 'evening' }" />
    </span>
  </div>
</template>

// packages/svelte/src/lib/components/format/examples/time-with-am-pm-labels.svelte
<script lang="ts">
  import { Format } from '@ark-ui/svelte/format'
  import styles from 'styles/format.module.css'
</script>

<div class={styles.Inline}>
  <span class={styles.InlineLabel}>Support window</span>
  <span class={styles.InlineValue}>
    <Format.Time value="17:15:00" format="12h" amPmLabels={{ am: 'morning', pm: 'evening' }} />
  </span>
</div>
